spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gpt_counselor
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  security:
    user:
      name: dlawjddn
      password: 1234

logging:
  level:
    web: debug

gpt:
  secret: ${GPT_KEY}
